services:
  shorts-engine:
    build: .
    container_name: shorts-engine
    volumes:
      # Mount the projects directory to persist generated videos
      - ./projects:/app/projects
      # Mount the assets directory for fonts and static assets
      - ./assets:/app/assets
      # Mount .env file for API keys and configuration
      - ./.env:/app/.env:ro
      # Mount Docker socket to allow container to use Docker
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONUNBUFFERED=1
    # Override the default command for interactive use
    # Remove this if you want to use the default --help
    # command: ["run-all", "test_project", "AI technology", "--version", "A"]
    
    # For development, you might want to mount the entire source code
    # Uncomment the line below for development mode
    # volumes:
    #   - .:/app
